# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WoofCommunity' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WoofCommunity
pod 'FirebaseAnalytics'
pod 'FirebaseAuth'
pod 'FirebaseFirestore'
pod 'FirebaseFirestoreSwift'
pod 'FirebaseCore'
pod 'Firebase/Auth'

end
